version: '3.8'

services:
  frontend:
    build:
      context: ./store-frontend
      dockerfile: Dockerfile
    container_name: store-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    # Uncomment the following if you have a backend API
    # depends_on:
    #  - api

  # Backend API service (uncomment and configure as needed)
  # api:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: store-api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=production
  #     # Add other environment variables as needed
  #   restart: unless-stopped
  #   depends_on:
  #     - db

  # Database service (uncomment and configure as needed)
  # db:
  #   image: postgres:13
  #   container_name: store-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: store
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   restart: unless-stopped

# Uncomment if you have a database service
# volumes:
#   db-data: 